version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hao3ub5ydmxf"
s3_prefix = "hello-world-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
